# Generated by Django 4.0.2 on 2022-03-08 12:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerDetails',
            fields=[
                ('UserId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.user')),
                ('PhoneNumber', models.CharField(max_length=11)),
                ('CompanyName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('TagId', models.AutoField(primary_key=True, serialize=False)),
                ('TagName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('VacancyId', models.AutoField(primary_key=True, serialize=False)),
                ('VacancyName', models.CharField(max_length=80)),
                ('Salary', models.CharField(max_length=80)),
                ('Description', models.CharField(max_length=150)),
                ('SkillsRequired', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=3)),
                ('ExperienceRequired', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=list, size=3)),
                ('TimeZone', models.IntegerField()),
                ('Tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=10)),
                ('IsOpen', models.BooleanField(default=True)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
    ]
