# Generated by Django 4.0.2 on 2022-03-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_vacancy_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerdetails',
            name='PhoneNumber',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='PhoneNumber',
            field=models.CharField(max_length=30),
        ),
    ]
