# Generated by Django 4.0.2 on 2022-03-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_alter_vacancy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='Location',
            field=models.CharField(default='', max_length=30),
        ),
    ]
