# Generated by Django 4.0.2 on 2022-04-14 12:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_vacancy_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='ExperienceRequired',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=75), default=list, size=3),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Location',
            field=models.CharField(max_length=30),
        ),
    ]
