# Generated by Django 4.0.2 on 2022-04-14 22:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_alter_vacancy_experiencerequired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='ExperienceRequired',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=3),
        ),
    ]
