# Generated by Django 4.0.2 on 2022-04-14 22:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0008_alter_vacancy_experiencerequired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='ExperienceRequired',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=75), blank=True, default=list, size=3),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=10),
        ),
    ]
