# Generated by Django 4.0.2 on 2022-04-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_alter_vacancy_experiencerequired_alter_vacancy_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='TagStyle',
            field=models.CharField(default='', max_length=30),
        ),
    ]
