# Generated by Django 4.0.2 on 2022-04-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_alter_vacancy_experiencerequired_alter_vacancy_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='Created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
