# Generated by Django 4.0.2 on 2022-04-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0010_alter_vacancy_created'),
        ('employer', '0010_tag_tagstyle'),
    ]

    operations = [
    ]
