# Generated by Django 4.0.2 on 2022-03-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('IsEmployer', models.BooleanField(default=False)),
                ('PasswordHash', models.CharField(max_length=500)),
                ('PasswordSalt', models.CharField(max_length=500)),
                ('PasswordResetToken', models.CharField(blank=True, max_length=100)),
                ('PasswordResetExpiration', models.DateField(blank=True)),
            ],
        ),
    ]
