# Generated by Django 4.0.2 on 2022-03-31 22:12

import authentication.helpers.jwt
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('TokenId', models.AutoField(primary_key=True, serialize=False)),
                ('FamilyId', models.IntegerField()),
                ('Token', models.CharField(max_length=200)),
                ('Expiry', models.DateTimeField(default=authentication.helpers.jwt.getAccessExpiry)),
            ],
        ),
    ]
