# Generated by Django 4.0.2 on 2022-04-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_passwordhash_remove_user_passwordsalt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='PasswordResetExpiration',
            field=models.DateTimeField(null=True),
        ),
    ]
