stages:
  - build
  - test
  - deploy

build-vue-client:
  stage: build
  tags:
    - node
  before_script:
    - cd client
  script:
    #- npm install --progress=false
    #- npm run build
    - echo 123

run-python-unit-tests:
  stage: test
  tags:
    - python
  before_script:
    - cd api
    - cp $ENV_FILE api/.env
  script:
    - apt-get update
    - apt-get install -y iputils-ping
    - ping 134.209.29.204
    - pip install -r requirements.txt
    # check db connection: DOESN'T WORK ATM
    #- python manage.py check --database default
    # run tests
    - coverage erase
    - coverage run --source='.' manage.py test
    - coverage report

run-js-unit-tests:
  stage: test
  tags:
    - node
  before_script:
    - cd client
  script:
    - npm i --include=dev
    - npm test

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
