stages:
  - build
  - test
  - deploy

build-django-job:
  stage: build
  script:
    - echo "Starting the api server..."
    - echo "API server started."

build-vue-job:
  stage: build
  script:
    - echo "Starting client server"
    - echo "Client server started"

python-unit-test-job:
  stage: test
  script:
    - echo "Running api unit tests... This will take about 20 seconds"
    - sleep 20
    - echo "Code coverage is 90%"

js-unit-test-job:
  stage: test
  script:
    - echo "Running client unit tests... This will take about 15 seconds"
    - sleep 15
    - echo "Code coverage is 75%"

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."