stages:
  - build
  - test
  - deploy

build-vue-client:
  stage: build
  tags:
    - node
    - server-runner
  only:
    refs:
      - main
  before_script:
    - cd client
  script:
    - npm install --progress=false
    - npm run build
  cache:
    paths:
      - client/node_modules/
  artifacts:
    paths:
      - client/
      - api/

run-python-unit-tests:
  stage: test
  tags:
    - python
    - server-runner
  before_script:
    - cd api
    - cp $TEST_ENV_FILE api/.env
  script:
    - pip install -r requirements.txt
    # have to install psycopg2 linux package separately
    - pip install psycopg2-binary
    # check db connection:
    - python manage.py check --database default
    # migrate db
    - python manage.py makemigrations employee employer authentication
    - python manage.py migrate employee 
    - python manage.py migrate employer
    - python manage.py migrate authentication
    # seed db
    - python manage.py flush --noinput
    - python manage.py loaddata fixtures.json
    # run tests
    - coverage erase
    - coverage run --source='.' manage.py test
    - coverage html
    - coverage xml
    - coverage report
  coverage: /TOTAL\s+\d+\s+\d+\s+(\d+%)/
  artifacts:
    paths:
      - api/htmlcov/
    reports:
      cobertura: api/coverage.xml

run-js-unit-tests:
  stage: test
  tags:
    - node
    - server-runner
  before_script:
    - cd client
  script:
    - npm i --include=dev
    - npm test
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  artifacts:
    paths:
      - client/tests/coverage/
    reports:
      cobertura: client/tests/cobertura-coverage.xml

deploy-api:
  stage: deploy
  tags:
    - python
    - server-runner
  only:
    refs:
      - main
  before_script:
    # add ssh private key to local .ssh
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-add
  script:
    - scp -r -o StrictHostKeyChecking=no
        $CI_PROJECT_DIR/api
        root@$SERVER_IP:/code
    # copy code and install packages
    - ssh root@$SERVER_IP "cd ../code/api && pip install -r requirements.txt && pip install psycopg2-binary"
    # copy env vars
    - cd api
    - cp $ENV_FILE api/.env
    - scp -o StrictHostKeyChecking=no
        $CI_PROJECT_DIR/api/api/.env
        root@$SERVER_IP:/code/api/api/.env
    # check db connection and make migrations:
    - ssh root@$SERVER_IP "cd /code/api && 
      python3 manage.py check --database default && 
      python3 manage.py makemigrations employee employer authentication && 
      python3 manage.py migrate employee &&
      python3 manage.py migrate employer && 
      python3 manage.py migrate authentication"
    # restart gunicorn and nginx servers
    - ssh root@$SERVER_IP "sudo systemctl restart gunicorn && sudo systemctl restart nginx"

deploy-client:
  stage: deploy
  tags:
    - node
    - server-runner
  only:
    refs:
      - main
  before_script:
    # add private ssh key to local .ssh
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-add
  script:
    - scp -o StrictHostKeyChecking=no -r client/dist/* root@$SERVER_IP:/code/client
    - ssh root@$SERVER_IP sudo service nginx reload