stages:
  - build
  - test
  - deploy

build-vue-client:
  stage: build
  tags:
    - node
    - server-runner
  before_script:
    - cd client
  script:
    - npm install --progress=false
    - npm run build

run-python-unit-tests:
  stage: test
  tags:
    - python
    - server-runner
  before_script:
    - cd api
    - cp $ENV_FILE api/.env
  script:
    - pip install -r requirements.txt
    # check db connection:
    - python manage.py check --database default
    # run tests
    - coverage erase
    - coverage run --source='.' manage.py test
    - coverage report

run-js-unit-tests:
  stage: test
  tags:
    - node
    - server-runner
  before_script:
    - cd client
  script:
    - npm i --include=dev
    - npm test

deploy:
  stage: deploy
  tags:
    - node
    - server-runner
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
