stages:
  - build
  - test
  - deploy

check-api-db-connection:
  stage: build
  tags:
    - python
  before_script:
    - cd api
    - cp $ENV_FILE api/.env
  script:
    - pip install -r requirements.txt
    #- python manage.py check --database default DOESN'T WORK ATM, CANNOT REACH DB

build-vue-client:
  stage: build
  tags:
    - node
  before_script:
    - cd client
  script:
    - npm install --progress=false
    - npm run build

python-unit-test-job:
  stage: test
  tags:
    - python
  before_script:
    - cd api
    - cp $ENV_FILE api/.env
  script:
    - pip install -r requirements.txt
    - coverage erase
    - coverage run --source='.' manage.py test
    - coverage report

js-unit-test-job:
  stage: test
  tags:
    - node
  script:
    - echo "Running client unit tests... This will take about 15 seconds"
    - sleep 15
    - echo "Code coverage is 75%"

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
