# Generated by Django 4.0.2 on 2022-03-08 12:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('UserId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.user')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Pronouns', models.CharField(max_length=50)),
                ('TimeZone', models.IntegerField()),
                ('TopicSentence', models.CharField(default='', max_length=200)),
                ('NotableSkills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=3)),
                ('Experience', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), default=list, size=3)),
                ('Qualifications', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), default=list, size=3)),
                ('PhoneNumber', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('FavouriteId', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
                ('VacancyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('ApplicationId', models.AutoField(primary_key=True, serialize=False)),
                ('ApplicationStatus', models.CharField(choices=[('MATCHED', 'Matched'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
                ('VacancyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.vacancy')),
            ],
        ),
    ]
