# Generated by Django 4.0.2 on 2022-03-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='PhoneNumber',
            field=models.CharField(max_length=30),
        ),
    ]
