# Generated by Django 4.0.2 on 2022-03-22 00:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_profile_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='LastUpdated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='Experience',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=3),
        ),
    ]
