# Generated by Django 4.0.2 on 2022-03-21 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_profile_phonenumber')
    ]

    operations = [
        migrations.CreateModel(
            name='Reject',
            fields=[
                ('RejectId', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
                ('VacancyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.vacancy')),
            ],
        ),
    ]
