# Generated by Django 4.0.2 on 2022-03-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_application_lastupdated_alter_profile_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='LastUpdated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
