# Generated by Django 4.0.2 on 2022-03-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_reject'),
        ('employee', '0004_alter_application_lastupdated'),
    ]

    operations = [
    ]
