# Generated by Django 4.0.2 on 2022-03-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_merge_0003_reject_0004_alter_application_lastupdated'),
        ('employee', '0005_profile_location'),
    ]

    operations = [
    ]
